### ISSUE TITLE
'Failed to load accounts.txt'

### ISSUE THREAD

**Issue by matthew-lowe** [MCGoSnipe/MCGoSnipe#3] opened 2021-02-13 20:37 UTC
Since 'accounts.txt' is in the .gitignore, I'm assuming it contains the account to snipe the name with, but there's nothing in the documentation about how it should be formatted or that it should be created in the first place.

**Comment by overestimate** [comment] 2021-02-21 07:07
Duplicate of #2.

**Closed by overestimate** 2021-02-21 07:07 UTC
Labels: duplicate

**Comment by overestimate** [comment] 2021-02-21 07:11
For reference, accounts should be loaded with the example shown in `accounts.txt.example`.
